services:
  - type: web
    name: flux-server
    env: docker
    region: ohio # Option to change: frankfurt, ohio, oregon, singapore
    plan: free # Free tier
    branch: main # Specify the branch if different
    dockerfilePath: ./server/Dockerfile
    dockerContext: ./server
    envVars:
      # Render assigns a dynamic port, so Gunicorn needs to bind to $PORT
      - key: PORT
        value: 9000
    # No need for ngrok tokens here, Render will generate a free public URL (e.g. flux-server.onrender.com)
